name: Build and deploy Users API to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: app-flapcloudgames-users-api
  PROJECT_FILE_PATH: FIAP.CloudGames.Customer.API/FIAP.CloudGames.Customer.API.csproj
  DOTNET_VERSION: '8.0.x'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore dependencies
        run: dotnet restore "${{ env.PROJECT_FILE_PATH }}"

      - name: Build project
        run: dotnet build "${{ env.PROJECT_FILE_PATH }}" --configuration Release --no-restore

      - name: Publish project
        run: dotnet publish "${{ env.PROJECT_FILE_PATH }}" --configuration Release --no-build --output "./publish"

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: "./publish"

      - name: Verify Swagger JSON
        run: |
          curl -sSf "https://${{ env.AZURE_WEBAPP_NAME }}.azurewebsites.net/swagger/v1/swagger.json" | head -n 20
