name: Build and Deploy Users API to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_WEBAPP_NAME: app-fiapcloudgames-users-api
  SOLUTION_FILE_PATH: Fiap.CloudGames.Users.sln

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout repo'
        uses: actions/checkout@v4

      - name: 'Setup .NET'
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: 'Restore dependencies'
        run: dotnet restore ${{ env.SOLUTION_FILE_PATH }}

      - name: 'Publish project'
        run: dotnet publish ${{ env.SOLUTION_FILE_PATH }} --configuration Release --output './publish'

      - name: 'Deploy to Azure App Service'
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: './publish'